FROM prefecthq/prefect:3.0.0rc14-python3.11

USER root

WORKDIR /app

COPY make/requirements.txt /tmp/requirements.txt

RUN apt-get update && \
    apt-get install -y curl git && \
    pip install --no-cache-dir -r /tmp/requirements.txt && \
    pip install --upgrade streamlit && \
    pip list && \  
    rm -rf /var/lib/apt/lists/*

COPY work /app

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]